@OpenData.Basketball.AbaLeague.API_HostAddress = http://localhost:8080
###
GET {{OpenData.Basketball.AbaLeague.API_HostAddress}}/api/league/scheduled?leagueId=3
Content-Type: application/json
Authorization: Bearer CfDJ8FRh-gaY2NpLugXHN1dP2PH8QyVzRKWQfZFmxJRuvJjIsqMTgdcd4JwFg_RJ3SwOXlbCl5vDVyiyb1f6GLum1GIWd90MlXBaKERv90KsJIMHdM4b-BYZIHWRivTRqAcB6fC8jYRClP4yGiUB8OBFFLjgyFemCirhXI7PRucfwnJ6oqJYm4RzWLf1yjoKrlYZ3wxMdBBbfCVv-eahPtYQf-L4nbpbEDc_72IRwwXrxKQ5jZZpuyqCvw0TXqQrtRAuyqYaCWCvET9sHzq3RLaMFG31VjC2T76JbqDJl8DjpTQx0_bTv0lcDT5aX6ajK8PN7OZcyMpwBP3kLmItt6iFiOEp5GJHYWdSOCog_Hxt91tx8rp218_UQ66SoaMPC_K_aQm5oT3wjAtdPGPbggfZDvGtJEyivXEJlbyWQytTITxKTO0GbvQYpfnMHqGExxgCwqhV3HUbplReJHFOfmxLCc8x29gRqf-TPAHqFsjUHyQv3xImhSA9p5f5dVR6ieS7t1UJyd7pG5_8x9Ck5rXdUaNAXE8bpNUUaCb-mpRGdIKUulT3vWRxQZMku165MJKoGxfqpIuIBwQpHUtMmc3yj7JI-BeqZg4wMCe95y3KSL89ufbN91UPv65co5ZjWg5ExsHF5n01IiCqIV-_cPox2N-MwpBqKtcz5vno9uL4HbyTNDab1NPBkDzylKP8HPQ20g

###
GET {{OpenData.Basketball.AbaLeague.API_HostAddress}}/api/league/scores?leagueId=3
Content-Type: application/json
Authorization: Bearer CfDJ8FRh-gaY2NpLugXHN1dP2PH8QyVzRKWQfZFmxJRuvJjIsqMTgdcd4JwFg_RJ3SwOXlbCl5vDVyiyb1f6GLum1GIWd90MlXBaKERv90KsJIMHdM4b-BYZIHWRivTRqAcB6fC8jYRClP4yGiUB8OBFFLjgyFemCirhXI7PRucfwnJ6oqJYm4RzWLf1yjoKrlYZ3wxMdBBbfCVv-eahPtYQf-L4nbpbEDc_72IRwwXrxKQ5jZZpuyqCvw0TXqQrtRAuyqYaCWCvET9sHzq3RLaMFG31VjC2T76JbqDJl8DjpTQx0_bTv0lcDT5aX6ajK8PN7OZcyMpwBP3kLmItt6iFiOEp5GJHYWdSOCog_Hxt91tx8rp218_UQ66SoaMPC_K_aQm5oT3wjAtdPGPbggfZDvGtJEyivXEJlbyWQytTITxKTO0GbvQYpfnMHqGExxgCwqhV3HUbplReJHFOfmxLCc8x29gRqf-TPAHqFsjUHyQv3xImhSA9p5f5dVR6ieS7t1UJyd7pG5_8x9Ck5rXdUaNAXE8bpNUUaCb-mpRGdIKUulT3vWRxQZMku165MJKoGxfqpIuIBwQpHUtMmc3yj7JI-BeqZg4wMCe95y3KSL89ufbN91UPv65co5ZjWg5ExsHF5n01IiCqIV-_cPox2N-MwpBqKtcz5vno9uL4HbyTNDab1NPBkDzylKP8HPQ20g
