@OpenData.Basketball.AbaLeague.API_HostAddress = http://localhost:8080
@ACCESS_JWT="CfDJ8FRh-gaY2NpLugXHN1dP2PHYMyo4-XG85yrg7q-hpvb21uoVoUJ0lCdwKzj50d-WN9YhMb-NnU_3FQyjZtKyD_OfXJbPgpMKYTx2VJgY3IhMWt_56-4Ckug9QzQFos8yWnqcnOnJQyCV0ToVz5WG1a4LByb_j4Wme-0f7eQFtUEjIQbrCDOCEDOKS0Pw0RsVpBQz0m6qShCgnJuS_9m8qFTHHZhSYy9ltDYZiOVA0Eo7E7dyqoYw7pxWwQZ5YuK5Ayflwr0AILy6KtU4iyz4rR01IzTC25HcnDqQAOh7mMIDUZ96sgx1REQMo9LsMfil-ApQazN0Rg7ZHX9TwcEjdI2_VeKp_4L_3jS1U4g3PsxL3TBHdg8M14M4_nTBPsTGgFwKrxFeqtDdTSpZYgO2EmwRdFLlqlyBNq3_arNwCgWOg5U3e42TrNrwKNZEbQDVSgM9b5DumNwSRd3JaLz82x0z6bsmC7jO9lPOufA0TNj5K3eQlFsN6ZtB42K3ZcBPGsbOm_IKHY2wT4bTGb_osEXyKcQmEUHQpZRfE9VsdXC1-r6GBldpEm7WGjYCnE8wgXK0lrnvzHcJEQxx_RCzaWFZ95y3vOKtpVKcttmgBENKk_ruz7YnqCW_7KdkwAMBw6WLdiUj6pLO9LdASlE8RwgukI4PQqABiifOcSvC6sHoqkPBUFXDNIEUWY_B9axbyw"
@EMAIL="string@test"
@PASSWORD="strinG1!"



POST {{OpenData.Basketball.AbaLeague.API_HostAddress}}/account/login
Content-Type: application/json

{
   "email": {{EMAIL}}, "password": {{PASSWORD}}
}
###

GET {{OpenData.Basketball.AbaLeague.API_HostAddress}}/api/season/all
Content-Type: application/json
Authorization: Bearer CfDJ8FRh-gaY2NpLugXHN1dP2PHYMyo4-XG85yrg7q-hpvb21uoVoUJ0lCdwKzj50d-WN9YhMb-NnU_3FQyjZtKyD_OfXJbPgpMKYTx2VJgY3IhMWt_56-4Ckug9QzQFos8yWnqcnOnJQyCV0ToVz5WG1a4LByb_j4Wme-0f7eQFtUEjIQbrCDOCEDOKS0Pw0RsVpBQz0m6qShCgnJuS_9m8qFTHHZhSYy9ltDYZiOVA0Eo7E7dyqoYw7pxWwQZ5YuK5Ayflwr0AILy6KtU4iyz4rR01IzTC25HcnDqQAOh7mMIDUZ96sgx1REQMo9LsMfil-ApQazN0Rg7ZHX9TwcEjdI2_VeKp_4L_3jS1U4g3PsxL3TBHdg8M14M4_nTBPsTGgFwKrxFeqtDdTSpZYgO2EmwRdFLlqlyBNq3_arNwCgWOg5U3e42TrNrwKNZEbQDVSgM9b5DumNwSRd3JaLz82x0z6bsmC7jO9lPOufA0TNj5K3eQlFsN6ZtB42K3ZcBPGsbOm_IKHY2wT4bTGb_osEXyKcQmEUHQpZRfE9VsdXC1-r6GBldpEm7WGjYCnE8wgXK0lrnvzHcJEQxx_RCzaWFZ95y3vOKtpVKcttmgBENKk_ruz7YnqCW_7KdkwAMBw6WLdiUj6pLO9LdASlE8RwgukI4PQqABiifOcSvC6sHoqkPBUFXDNIEUWY_B9axbyw

###

GET {{OpenData.Basketball.AbaLeague.API_HostAddress}}/api/league/all
Content-Type: application/json
Authorization: Bearer CfDJ8FRh-gaY2NpLugXHN1dP2PE09S0YLZ-fXebHak_LIFMFFY7OlKdwFAOh0S3WFpMv13GzYHWwvbjXbGZoCFWXxNHBHr8ot13sdH1q4gHHNsIPi9g5EOkNchBHtqJtgnqCfWgeLVSi27H88bMimp70T2Zx2hmt3KIVv0BMMv2rlO1FBmqHFIFgkdeZ5j4rPMFftol3077dbcumeRA0UmD-NyA2MVsaPxGFlc9iHnHkQEa2d3AVEGVZF3hRNlDp1HYUAxorv0nbC5e3ZftkGbfJgRo_3eU8Ux3lbawuy8hBWxp574SkKkw50-52LRvMvC9yTMko9F9o3ZPmknvRSgHz7hHwxyVAY-5Y_wrN1Hj6-qfFC8pJ7k5lK-F8LdhxuOeMb67mjKxXlJJSvXqfx8b5zkhTy_CakHdg3E_3OHFPpvLrf8C38Y0H_d_kcRhS5jaj2zv9pcUaLZk5AQ6sWP-PhBsR7WfK4h2wUV5dg47esbcfAwjQiKWTZpOv-8_7uP0XoDJr_JtM_pkOquC4PRFleb4tDUKKSW_QrSIHev4LoKa8fSIUsEic8uV1ahzkcyOlYG-pp0DSSFWlfVBOVIOYN0MtvkSi5e3d8GGkrEUWNGFAGAiQnQTuTf9p6yqmK6FJf3onJawPVPEzhvztWAVTjxBnmFxwAMiC2Z6IlXCNjuV-2MdFvMhm_y1eax77l0Mykw

###

GET {{OpenData.Basketball.AbaLeague.API_HostAddress}}/api/league/standings?leagueId=3
Content-Type: application/json
Authorization: Bearer CfDJ8FRh-gaY2NpLugXHN1dP2PE09S0YLZ-fXebHak_LIFMFFY7OlKdwFAOh0S3WFpMv13GzYHWwvbjXbGZoCFWXxNHBHr8ot13sdH1q4gHHNsIPi9g5EOkNchBHtqJtgnqCfWgeLVSi27H88bMimp70T2Zx2hmt3KIVv0BMMv2rlO1FBmqHFIFgkdeZ5j4rPMFftol3077dbcumeRA0UmD-NyA2MVsaPxGFlc9iHnHkQEa2d3AVEGVZF3hRNlDp1HYUAxorv0nbC5e3ZftkGbfJgRo_3eU8Ux3lbawuy8hBWxp574SkKkw50-52LRvMvC9yTMko9F9o3ZPmknvRSgHz7hHwxyVAY-5Y_wrN1Hj6-qfFC8pJ7k5lK-F8LdhxuOeMb67mjKxXlJJSvXqfx8b5zkhTy_CakHdg3E_3OHFPpvLrf8C38Y0H_d_kcRhS5jaj2zv9pcUaLZk5AQ6sWP-PhBsR7WfK4h2wUV5dg47esbcfAwjQiKWTZpOv-8_7uP0XoDJr_JtM_pkOquC4PRFleb4tDUKKSW_QrSIHev4LoKa8fSIUsEic8uV1ahzkcyOlYG-pp0DSSFWlfVBOVIOYN0MtvkSi5e3d8GGkrEUWNGFAGAiQnQTuTf9p6yqmK6FJf3onJawPVPEzhvztWAVTjxBnmFxwAMiC2Z6IlXCNjuV-2MdFvMhm_y1eax77l0Mykw

###

GET {{OpenData.Basketball.AbaLeague.API_HostAddress}}/api/league?leagueId=33
Content-Type: application/json
Authorization: Bearer CfDJ8FRh-gaY2NpLugXHN1dP2PE09S0YLZ-fXebHak_LIFMFFY7OlKdwFAOh0S3WFpMv13GzYHWwvbjXbGZoCFWXxNHBHr8ot13sdH1q4gHHNsIPi9g5EOkNchBHtqJtgnqCfWgeLVSi27H88bMimp70T2Zx2hmt3KIVv0BMMv2rlO1FBmqHFIFgkdeZ5j4rPMFftol3077dbcumeRA0UmD-NyA2MVsaPxGFlc9iHnHkQEa2d3AVEGVZF3hRNlDp1HYUAxorv0nbC5e3ZftkGbfJgRo_3eU8Ux3lbawuy8hBWxp574SkKkw50-52LRvMvC9yTMko9F9o3ZPmknvRSgHz7hHwxyVAY-5Y_wrN1Hj6-qfFC8pJ7k5lK-F8LdhxuOeMb67mjKxXlJJSvXqfx8b5zkhTy_CakHdg3E_3OHFPpvLrf8C38Y0H_d_kcRhS5jaj2zv9pcUaLZk5AQ6sWP-PhBsR7WfK4h2wUV5dg47esbcfAwjQiKWTZpOv-8_7uP0XoDJr_JtM_pkOquC4PRFleb4tDUKKSW_QrSIHev4LoKa8fSIUsEic8uV1ahzkcyOlYG-pp0DSSFWlfVBOVIOYN0MtvkSi5e3d8GGkrEUWNGFAGAiQnQTuTf9p6yqmK6FJf3onJawPVPEzhvztWAVTjxBnmFxwAMiC2Z6IlXCNjuV-2MdFvMhm_y1eax77l0Mykw

###