@OpenData.Basketball.AbaLeague.API_HostAddress = http://localhost:8080
@ACCESS_JWT="CfDJ8FRh-gaY2NpLugXHN1dP2PHYMyo4-XG85yrg7q-hpvb21uoVoUJ0lCdwKzj50d-WN9YhMb-NnU_3FQyjZtKyD_OfXJbPgpMKYTx2VJgY3IhMWt_56-4Ckug9QzQFos8yWnqcnOnJQyCV0ToVz5WG1a4LByb_j4Wme-0f7eQFtUEjIQbrCDOCEDOKS0Pw0RsVpBQz0m6qShCgnJuS_9m8qFTHHZhSYy9ltDYZiOVA0Eo7E7dyqoYw7pxWwQZ5YuK5Ayflwr0AILy6KtU4iyz4rR01IzTC25HcnDqQAOh7mMIDUZ96sgx1REQMo9LsMfil-ApQazN0Rg7ZHX9TwcEjdI2_VeKp_4L_3jS1U4g3PsxL3TBHdg8M14M4_nTBPsTGgFwKrxFeqtDdTSpZYgO2EmwRdFLlqlyBNq3_arNwCgWOg5U3e42TrNrwKNZEbQDVSgM9b5DumNwSRd3JaLz82x0z6bsmC7jO9lPOufA0TNj5K3eQlFsN6ZtB42K3ZcBPGsbOm_IKHY2wT4bTGb_osEXyKcQmEUHQpZRfE9VsdXC1-r6GBldpEm7WGjYCnE8wgXK0lrnvzHcJEQxx_RCzaWFZ95y3vOKtpVKcttmgBENKk_ruz7YnqCW_7KdkwAMBw6WLdiUj6pLO9LdASlE8RwgukI4PQqABiifOcSvC6sHoqkPBUFXDNIEUWY_B9axbyw"
@EMAIL="string@test"
@PASSWORD="strinG1!"



POST {{OpenData.Basketball.AbaLeague.API_HostAddress}}/account/login
Content-Type: application/json

{
   "email": {{EMAIL}}, "password": {{PASSWORD}}
}
###

GET {{OpenData.Basketball.AbaLeague.API_HostAddress}}/api/season/all
Content-Type: application/json
Authorization: Bearer CfDJ8FRh-gaY2NpLugXHN1dP2PHYMyo4-XG85yrg7q-hpvb21uoVoUJ0lCdwKzj50d-WN9YhMb-NnU_3FQyjZtKyD_OfXJbPgpMKYTx2VJgY3IhMWt_56-4Ckug9QzQFos8yWnqcnOnJQyCV0ToVz5WG1a4LByb_j4Wme-0f7eQFtUEjIQbrCDOCEDOKS0Pw0RsVpBQz0m6qShCgnJuS_9m8qFTHHZhSYy9ltDYZiOVA0Eo7E7dyqoYw7pxWwQZ5YuK5Ayflwr0AILy6KtU4iyz4rR01IzTC25HcnDqQAOh7mMIDUZ96sgx1REQMo9LsMfil-ApQazN0Rg7ZHX9TwcEjdI2_VeKp_4L_3jS1U4g3PsxL3TBHdg8M14M4_nTBPsTGgFwKrxFeqtDdTSpZYgO2EmwRdFLlqlyBNq3_arNwCgWOg5U3e42TrNrwKNZEbQDVSgM9b5DumNwSRd3JaLz82x0z6bsmC7jO9lPOufA0TNj5K3eQlFsN6ZtB42K3ZcBPGsbOm_IKHY2wT4bTGb_osEXyKcQmEUHQpZRfE9VsdXC1-r6GBldpEm7WGjYCnE8wgXK0lrnvzHcJEQxx_RCzaWFZ95y3vOKtpVKcttmgBENKk_ruz7YnqCW_7KdkwAMBw6WLdiUj6pLO9LdASlE8RwgukI4PQqABiifOcSvC6sHoqkPBUFXDNIEUWY_B9axbyw

###

GET {{OpenData.Basketball.AbaLeague.API_HostAddress}}/api/season?seasonId=1
Content-Type: application/json
Authorization: Bearer CfDJ8FRh-gaY2NpLugXHN1dP2PHIUypnY2H8THaoTHA6wWzZHbbcUNxCKm0FZIlvFGFKAaE-0vLnuzAszLVLp16BFVJgFQobV99EEc33E5_qspbO64pJsf-59_INLCr7k73pVeH07dyCDySSUZijHRxTnEuVy8he0KZFI_6IjlhOs8MhRO-CTJQRBf7Xdnmgv_y730WfUZ_V5ob2UdRdWE3LPziLJz6stywDGJowgrRaSoySmShaS4t6FJ6y9nbWo9-oLVlNGwF89dvSi3LKHf9RQUp28-phIUrYHrBp_bZ81DuM72WnIX-w6czMbZ_n-w_U38LxMjznHChyaVugMn7AGWYQZQrUosr7Jbv20hjAJEhyTIeHeF5F99WY3jxgmBHtgk4tUvILu3AtBmuemb1HauhZyf18Rp7Vnw9IIVaIHdtBlIaw8tC4Qna6j7pIYtSN5IByAuRYwc4lkX4i3kITBcTXabZCDR9ot1KhrAXU2-sycFE7ZCGS84UW4PvAshGFVzQKYhkOB7ZuWB-4M57i7eqy7j1ONlQ9s-2uRUGi_Evjo26IufafjA5MaTeMQyt0sWEkIk2nu9mWMSNRhwV-ZK9cPqp1Z39_hcTqiNXJDK91vuE7e2O7zbbEW9ic-BA6L3VqcIrhS6qSIZjlMtkuycP1XLQrvLz9kVCzLCGvJTrXa_3Qgeb7O4UstSZhp304zw

###

GET {{OpenData.Basketball.AbaLeague.API_HostAddress}}/api/league/all
Content-Type: application/json
Authorization: Bearer CfDJ8FRh-gaY2NpLugXHN1dP2PE09S0YLZ-fXebHak_LIFMFFY7OlKdwFAOh0S3WFpMv13GzYHWwvbjXbGZoCFWXxNHBHr8ot13sdH1q4gHHNsIPi9g5EOkNchBHtqJtgnqCfWgeLVSi27H88bMimp70T2Zx2hmt3KIVv0BMMv2rlO1FBmqHFIFgkdeZ5j4rPMFftol3077dbcumeRA0UmD-NyA2MVsaPxGFlc9iHnHkQEa2d3AVEGVZF3hRNlDp1HYUAxorv0nbC5e3ZftkGbfJgRo_3eU8Ux3lbawuy8hBWxp574SkKkw50-52LRvMvC9yTMko9F9o3ZPmknvRSgHz7hHwxyVAY-5Y_wrN1Hj6-qfFC8pJ7k5lK-F8LdhxuOeMb67mjKxXlJJSvXqfx8b5zkhTy_CakHdg3E_3OHFPpvLrf8C38Y0H_d_kcRhS5jaj2zv9pcUaLZk5AQ6sWP-PhBsR7WfK4h2wUV5dg47esbcfAwjQiKWTZpOv-8_7uP0XoDJr_JtM_pkOquC4PRFleb4tDUKKSW_QrSIHev4LoKa8fSIUsEic8uV1ahzkcyOlYG-pp0DSSFWlfVBOVIOYN0MtvkSi5e3d8GGkrEUWNGFAGAiQnQTuTf9p6yqmK6FJf3onJawPVPEzhvztWAVTjxBnmFxwAMiC2Z6IlXCNjuV-2MdFvMhm_y1eax77l0Mykw

###

GET {{OpenData.Basketball.AbaLeague.API_HostAddress}}/api/league/standings?leagueId=3
Content-Type: application/json
Authorization: Bearer CfDJ8FRh-gaY2NpLugXHN1dP2PHpOmLJUfxi0EF6dUj68yw3_1hQ4dBg70wd4k8ITrae4_Ypzk8y3uavTkNd5UT1_G6jjv9bx-T8HH6p9Un_Wb4FUKQYvEIJJBv3N84_3_0Z3fhAl4axnCywPuYCBBKNddRngXrzV3sI4-TKGQlxz8y16q2ltpRue9Zl74V3vMvxRNblRvywcQ0-t2u3LMloNsNS24klUbV7d-iEus2xa92UeYQak7KQW2Y6XBHcJI6DhNQPHfpsXtgXm5E2jwyWvjmc-BaBwKRmEn6ylyncNtxtpo07px3EHGWF1M4l4GEOTpx9OEnBzqTiH_f98oN0ou1Y3QVqxhLZ4Cue9P6g77LHp92MeSxQBLMDk1Hzgf4A-AMygdlCMc88mVbJOYL2kvpLutoeYQpSuZFccBPTRclgUA44r-k0hRti90XmVzobl6eF4WAPOCWeoEuO66XgAQxfVP6EADcnXNRkNZA93xQ-_N5VzOQRQtlND7S9dLG_Pt6U9vrppPUMO8puiZppJ6eZAvSkcFKo1vIZSFO4ykCH6snJMlfgKmCN_WPYRIMJ9ggfBBLAWKk1bz8Wih6sMl2kc2ilOuY4nY-bzljlsAqNRmCqrmOPmP1gKdlDHtpb4ytPrkYiTm_BnD1aGEdkgGmgOeZKaAkSqdotUp8I9t2YNyfP6xsa8uOw37FdQ7f1aA

###

GET {{OpenData.Basketball.AbaLeague.API_HostAddress}}/api/league?leagueId=3
Content-Type: application/json
Authorization: Bearer CfDJ8FRh-gaY2NpLugXHN1dP2PE09S0YLZ-fXebHak_LIFMFFY7OlKdwFAOh0S3WFpMv13GzYHWwvbjXbGZoCFWXxNHBHr8ot13sdH1q4gHHNsIPi9g5EOkNchBHtqJtgnqCfWgeLVSi27H88bMimp70T2Zx2hmt3KIVv0BMMv2rlO1FBmqHFIFgkdeZ5j4rPMFftol3077dbcumeRA0UmD-NyA2MVsaPxGFlc9iHnHkQEa2d3AVEGVZF3hRNlDp1HYUAxorv0nbC5e3ZftkGbfJgRo_3eU8Ux3lbawuy8hBWxp574SkKkw50-52LRvMvC9yTMko9F9o3ZPmknvRSgHz7hHwxyVAY-5Y_wrN1Hj6-qfFC8pJ7k5lK-F8LdhxuOeMb67mjKxXlJJSvXqfx8b5zkhTy_CakHdg3E_3OHFPpvLrf8C38Y0H_d_kcRhS5jaj2zv9pcUaLZk5AQ6sWP-PhBsR7WfK4h2wUV5dg47esbcfAwjQiKWTZpOv-8_7uP0XoDJr_JtM_pkOquC4PRFleb4tDUKKSW_QrSIHev4LoKa8fSIUsEic8uV1ahzkcyOlYG-pp0DSSFWlfVBOVIOYN0MtvkSi5e3d8GGkrEUWNGFAGAiQnQTuTf9p6yqmK6FJf3onJawPVPEzhvztWAVTjxBnmFxwAMiC2Z6IlXCNjuV-2MdFvMhm_y1eax77l0Mykw

###

GET {{OpenData.Basketball.AbaLeague.API_HostAddress}}/api/team/all
Content-Type: application/json
Authorization: Bearer CfDJ8FRh-gaY2NpLugXHN1dP2PE09S0YLZ-fXebHak_LIFMFFY7OlKdwFAOh0S3WFpMv13GzYHWwvbjXbGZoCFWXxNHBHr8ot13sdH1q4gHHNsIPi9g5EOkNchBHtqJtgnqCfWgeLVSi27H88bMimp70T2Zx2hmt3KIVv0BMMv2rlO1FBmqHFIFgkdeZ5j4rPMFftol3077dbcumeRA0UmD-NyA2MVsaPxGFlc9iHnHkQEa2d3AVEGVZF3hRNlDp1HYUAxorv0nbC5e3ZftkGbfJgRo_3eU8Ux3lbawuy8hBWxp574SkKkw50-52LRvMvC9yTMko9F9o3ZPmknvRSgHz7hHwxyVAY-5Y_wrN1Hj6-qfFC8pJ7k5lK-F8LdhxuOeMb67mjKxXlJJSvXqfx8b5zkhTy_CakHdg3E_3OHFPpvLrf8C38Y0H_d_kcRhS5jaj2zv9pcUaLZk5AQ6sWP-PhBsR7WfK4h2wUV5dg47esbcfAwjQiKWTZpOv-8_7uP0XoDJr_JtM_pkOquC4PRFleb4tDUKKSW_QrSIHev4LoKa8fSIUsEic8uV1ahzkcyOlYG-pp0DSSFWlfVBOVIOYN0MtvkSi5e3d8GGkrEUWNGFAGAiQnQTuTf9p6yqmK6FJf3onJawPVPEzhvztWAVTjxBnmFxwAMiC2Z6IlXCNjuV-2MdFvMhm_y1eax77l0Mykw

###

GET {{OpenData.Basketball.AbaLeague.API_HostAddress}}/api/team?teamId=49
Content-Type: application/json
Authorization: Bearer CfDJ8FRh-gaY2NpLugXHN1dP2PE09S0YLZ-fXebHak_LIFMFFY7OlKdwFAOh0S3WFpMv13GzYHWwvbjXbGZoCFWXxNHBHr8ot13sdH1q4gHHNsIPi9g5EOkNchBHtqJtgnqCfWgeLVSi27H88bMimp70T2Zx2hmt3KIVv0BMMv2rlO1FBmqHFIFgkdeZ5j4rPMFftol3077dbcumeRA0UmD-NyA2MVsaPxGFlc9iHnHkQEa2d3AVEGVZF3hRNlDp1HYUAxorv0nbC5e3ZftkGbfJgRo_3eU8Ux3lbawuy8hBWxp574SkKkw50-52LRvMvC9yTMko9F9o3ZPmknvRSgHz7hHwxyVAY-5Y_wrN1Hj6-qfFC8pJ7k5lK-F8LdhxuOeMb67mjKxXlJJSvXqfx8b5zkhTy_CakHdg3E_3OHFPpvLrf8C38Y0H_d_kcRhS5jaj2zv9pcUaLZk5AQ6sWP-PhBsR7WfK4h2wUV5dg47esbcfAwjQiKWTZpOv-8_7uP0XoDJr_JtM_pkOquC4PRFleb4tDUKKSW_QrSIHev4LoKa8fSIUsEic8uV1ahzkcyOlYG-pp0DSSFWlfVBOVIOYN0MtvkSi5e3d8GGkrEUWNGFAGAiQnQTuTf9p6yqmK6FJf3onJawPVPEzhvztWAVTjxBnmFxwAMiC2Z6IlXCNjuV-2MdFvMhm_y1eax77l0Mykw

###