@OpenData.Basketball.AbaLeague.API_HostAddress = http://localhost:8080

GET {{OpenData.Basketball.AbaLeague.API_HostAddress}}/api/team/all
Content-Type: application/json
Authorization: Bearer CfDJ8FRh-gaY2NpLugXHN1dP2PHpOmLJUfxi0EF6dUj68yw3_1hQ4dBg70wd4k8ITrae4_Ypzk8y3uavTkNd5UT1_G6jjv9bx-T8HH6p9Un_Wb4FUKQYvEIJJBv3N84_3_0Z3fhAl4axnCywPuYCBBKNddRngXrzV3sI4-TKGQlxz8y16q2ltpRue9Zl74V3vMvxRNblRvywcQ0-t2u3LMloNsNS24klUbV7d-iEus2xa92UeYQak7KQW2Y6XBHcJI6DhNQPHfpsXtgXm5E2jwyWvjmc-BaBwKRmEn6ylyncNtxtpo07px3EHGWF1M4l4GEOTpx9OEnBzqTiH_f98oN0ou1Y3QVqxhLZ4Cue9P6g77LHp92MeSxQBLMDk1Hzgf4A-AMygdlCMc88mVbJOYL2kvpLutoeYQpSuZFccBPTRclgUA44r-k0hRti90XmVzobl6eF4WAPOCWeoEuO66XgAQxfVP6EADcnXNRkNZA93xQ-_N5VzOQRQtlND7S9dLG_Pt6U9vrppPUMO8puiZppJ6eZAvSkcFKo1vIZSFO4ykCH6snJMlfgKmCN_WPYRIMJ9ggfBBLAWKk1bz8Wih6sMl2kc2ilOuY4nY-bzljlsAqNRmCqrmOPmP1gKdlDHtpb4ytPrkYiTm_BnD1aGEdkgGmgOeZKaAkSqdotUp8I9t2YNyfP6xsa8uOw37FdQ7f1aA

###

GET {{OpenData.Basketball.AbaLeague.API_HostAddress}}/api/team?teamId=1
Content-Type: application/json
Authorization: Bearer CfDJ8FRh-gaY2NpLugXHN1dP2PHpOmLJUfxi0EF6dUj68yw3_1hQ4dBg70wd4k8ITrae4_Ypzk8y3uavTkNd5UT1_G6jjv9bx-T8HH6p9Un_Wb4FUKQYvEIJJBv3N84_3_0Z3fhAl4axnCywPuYCBBKNddRngXrzV3sI4-TKGQlxz8y16q2ltpRue9Zl74V3vMvxRNblRvywcQ0-t2u3LMloNsNS24klUbV7d-iEus2xa92UeYQak7KQW2Y6XBHcJI6DhNQPHfpsXtgXm5E2jwyWvjmc-BaBwKRmEn6ylyncNtxtpo07px3EHGWF1M4l4GEOTpx9OEnBzqTiH_f98oN0ou1Y3QVqxhLZ4Cue9P6g77LHp92MeSxQBLMDk1Hzgf4A-AMygdlCMc88mVbJOYL2kvpLutoeYQpSuZFccBPTRclgUA44r-k0hRti90XmVzobl6eF4WAPOCWeoEuO66XgAQxfVP6EADcnXNRkNZA93xQ-_N5VzOQRQtlND7S9dLG_Pt6U9vrppPUMO8puiZppJ6eZAvSkcFKo1vIZSFO4ykCH6snJMlfgKmCN_WPYRIMJ9ggfBBLAWKk1bz8Wih6sMl2kc2ilOuY4nY-bzljlsAqNRmCqrmOPmP1gKdlDHtpb4ytPrkYiTm_BnD1aGEdkgGmgOeZKaAkSqdotUp8I9t2YNyfP6xsa8uOw37FdQ7f1aA

###

GET {{OpenData.Basketball.AbaLeague.API_HostAddress}}/api/team/performanceByLeague?teamId=1&leagueId=3
Content-Type: application/json
Authorization: Bearer CfDJ8FRh-gaY2NpLugXHN1dP2PHpOmLJUfxi0EF6dUj68yw3_1hQ4dBg70wd4k8ITrae4_Ypzk8y3uavTkNd5UT1_G6jjv9bx-T8HH6p9Un_Wb4FUKQYvEIJJBv3N84_3_0Z3fhAl4axnCywPuYCBBKNddRngXrzV3sI4-TKGQlxz8y16q2ltpRue9Zl74V3vMvxRNblRvywcQ0-t2u3LMloNsNS24klUbV7d-iEus2xa92UeYQak7KQW2Y6XBHcJI6DhNQPHfpsXtgXm5E2jwyWvjmc-BaBwKRmEn6ylyncNtxtpo07px3EHGWF1M4l4GEOTpx9OEnBzqTiH_f98oN0ou1Y3QVqxhLZ4Cue9P6g77LHp92MeSxQBLMDk1Hzgf4A-AMygdlCMc88mVbJOYL2kvpLutoeYQpSuZFccBPTRclgUA44r-k0hRti90XmVzobl6eF4WAPOCWeoEuO66XgAQxfVP6EADcnXNRkNZA93xQ-_N5VzOQRQtlND7S9dLG_Pt6U9vrppPUMO8puiZppJ6eZAvSkcFKo1vIZSFO4ykCH6snJMlfgKmCN_WPYRIMJ9ggfBBLAWKk1bz8Wih6sMl2kc2ilOuY4nY-bzljlsAqNRmCqrmOPmP1gKdlDHtpb4ytPrkYiTm_BnD1aGEdkgGmgOeZKaAkSqdotUp8I9t2YNyfP6xsa8uOw37FdQ7f1aA

###
GET {{OpenData.Basketball.AbaLeague.API_HostAddress}}/api/team/roster?teamId=49
Content-Type: application/json
Authorization: Bearer CfDJ8FRh-gaY2NpLugXHN1dP2PHpOmLJUfxi0EF6dUj68yw3_1hQ4dBg70wd4k8ITrae4_Ypzk8y3uavTkNd5UT1_G6jjv9bx-T8HH6p9Un_Wb4FUKQYvEIJJBv3N84_3_0Z3fhAl4axnCywPuYCBBKNddRngXrzV3sI4-TKGQlxz8y16q2ltpRue9Zl74V3vMvxRNblRvywcQ0-t2u3LMloNsNS24klUbV7d-iEus2xa92UeYQak7KQW2Y6XBHcJI6DhNQPHfpsXtgXm5E2jwyWvjmc-BaBwKRmEn6ylyncNtxtpo07px3EHGWF1M4l4GEOTpx9OEnBzqTiH_f98oN0ou1Y3QVqxhLZ4Cue9P6g77LHp92MeSxQBLMDk1Hzgf4A-AMygdlCMc88mVbJOYL2kvpLutoeYQpSuZFccBPTRclgUA44r-k0hRti90XmVzobl6eF4WAPOCWeoEuO66XgAQxfVP6EADcnXNRkNZA93xQ-_N5VzOQRQtlND7S9dLG_Pt6U9vrppPUMO8puiZppJ6eZAvSkcFKo1vIZSFO4ykCH6snJMlfgKmCN_WPYRIMJ9ggfBBLAWKk1bz8Wih6sMl2kc2ilOuY4nY-bzljlsAqNRmCqrmOPmP1gKdlDHtpb4ytPrkYiTm_BnD1aGEdkgGmgOeZKaAkSqdotUp8I9t2YNyfP6xsa8uOw37FdQ7f1aA

###

GET {{OpenData.Basketball.AbaLeague.API_HostAddress}}/api/team/rosterHistory?teamId=49
Content-Type: application/json
Authorization: Bearer CfDJ8FRh-gaY2NpLugXHN1dP2PHpOmLJUfxi0EF6dUj68yw3_1hQ4dBg70wd4k8ITrae4_Ypzk8y3uavTkNd5UT1_G6jjv9bx-T8HH6p9Un_Wb4FUKQYvEIJJBv3N84_3_0Z3fhAl4axnCywPuYCBBKNddRngXrzV3sI4-TKGQlxz8y16q2ltpRue9Zl74V3vMvxRNblRvywcQ0-t2u3LMloNsNS24klUbV7d-iEus2xa92UeYQak7KQW2Y6XBHcJI6DhNQPHfpsXtgXm5E2jwyWvjmc-BaBwKRmEn6ylyncNtxtpo07px3EHGWF1M4l4GEOTpx9OEnBzqTiH_f98oN0ou1Y3QVqxhLZ4Cue9P6g77LHp92MeSxQBLMDk1Hzgf4A-AMygdlCMc88mVbJOYL2kvpLutoeYQpSuZFccBPTRclgUA44r-k0hRti90XmVzobl6eF4WAPOCWeoEuO66XgAQxfVP6EADcnXNRkNZA93xQ-_N5VzOQRQtlND7S9dLG_Pt6U9vrppPUMO8puiZppJ6eZAvSkcFKo1vIZSFO4ykCH6snJMlfgKmCN_WPYRIMJ9ggfBBLAWKk1bz8Wih6sMl2kc2ilOuY4nY-bzljlsAqNRmCqrmOPmP1gKdlDHtpb4ytPrkYiTm_BnD1aGEdkgGmgOeZKaAkSqdotUp8I9t2YNyfP6xsa8uOw37FdQ7f1aA

###